import { currentIdToken } from '@/app/providers/use-auth-storage';
import { API_BASE_URL } from '@/services/constants';
import { API_401_EVENT } from '@/app/providers/auth-provider';
import { HTTPValidationError } from '@/api/methods.schemas';

/** Error raised when the FastAPI backend returned a Pydantic HTTPValidationError. */
export class ApiValidationError extends Error {
  public readonly data: HTTPValidationError;
  public readonly status: 422;

  constructor(response: { status: 422; data: HTTPValidationError }) {
    super(`API 422 Error: ${response.status}`);
    Object.setPrototypeOf(this, ApiValidationError.prototype);
    this.data = response.data;
    this.status = response.status;
    this.name = 'ApiValidationError';
  }
}
/**
 * Error raised when the FastAPI backend returned an unsuccessful response.
 */
export class ApiError extends Error {
  constructor(public readonly response: { status: number; data: unknown }) {
    super(`API Error: ${response}`);
    Object.setPrototypeOf(this, ApiError.prototype);
    this.name = 'ApiUnsuccessfulError';
  }
}

const getBody = (c: Response) => {
  const contentType = c.headers.get('content-type');
  if (contentType && contentType.includes('application/json')) {
    return c.json();
  }
  if (contentType && contentType.includes('text/csv')) {
    return c.text();
  }
  if (c.status === 204) {
    return null;
  }
  throw Error('Backend returned unsupported content-type.');
};

const getHeaders = (options: RequestInit) => {
  const idToken = currentIdToken();
  return {
    ...options.headers,
    'Content-Type': 'application/json',
    ...(idToken && { Authorization: 'Bearer ' + idToken }),
  };
};

const sendCustomLogoutEvent = () => {
  window.dispatchEvent(new CustomEvent(API_401_EVENT));
};

export const orvalFetch = async <T>(path: string, options: RequestInit): Promise<T> => {
  const requestUrl = new URL(path, API_BASE_URL);
  const requestInit: RequestInit = {
    ...options,
    headers: getHeaders(options),
  };
  const request = new Request(requestUrl, requestInit);
  const response = await fetch(request);
  const data = await getBody(response);

  if (request.headers.has('Authorization') && response.status === 401) {
    // Orval doesn't allow us to pass through context so we cannot invoke the logout() handler directly; instead,
    // we trigger a custom event which auth-provider will react to.
    sendCustomLogoutEvent();
  }
  const result = { status: response.status, data: data, headers: response.headers };
  if (result.status === 422 && result.data.detail?.length > 0) {
    throw new ApiValidationError({ ...result, status: 422 });
  } else if (response.status < 200 || response.status >= 300) {
    throw new ApiError(result);
  }
  return data;
};

// Orval's generated clients assume that the payloads of error responses correspond to generated types, so it refers to
// ErrorType<P>; when P can be known (such as 422s), it will specify that type as P. In other cases, it uses unknown.
// However, our backend behavior has failure behavior that are not defined in the OpenAPI spec generated by FastAPI, so
// we disregard the generated type for error payloads because Orval does not generate all possible responses.
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ErrorType<GeneratedErrorPayload> = Error | ApiValidationError | ApiError;
