/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * xngin: Experiments API
 * OpenAPI spec version: 0.9.0
 */
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";

import type {
	AuthCallbackParams,
	CallbackResponse,
	HTTPValidationError,
} from "./methods.schemas";

import { orvalFetch } from "../services/orval-fetch";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * OAuth callback endpoint that exchanges the authorization code for tokens, and returns the id_token to the client.

Only relevant for PKCE.
 * @summary Auth Callback
 */
export type authCallbackResponse200 = {
	data: CallbackResponse;
	status: 200;
};

export type authCallbackResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type authCallbackResponseComposite =
	| authCallbackResponse200
	| authCallbackResponse422;

export type authCallbackResponse = authCallbackResponseComposite & {
	headers: Headers;
};

export const getAuthCallbackUrl = (params: AuthCallbackParams) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `/v1/a/oidc/callback?${stringifiedParams}`
		: `/v1/a/oidc/callback`;
};

export const authCallback = async (
	params: AuthCallbackParams,
	options?: RequestInit,
): Promise<authCallbackResponse> => {
	return orvalFetch<authCallbackResponse>(getAuthCallbackUrl(params), {
		...options,
		method: "GET",
	});
};

export const getAuthCallbackKey = (params: AuthCallbackParams) =>
	[`/v1/a/oidc/callback`, ...(params ? [params] : [])] as const;

export type AuthCallbackQueryResult = NonNullable<
	Awaited<ReturnType<typeof authCallback>>
>;
export type AuthCallbackQueryError = HTTPValidationError;

/**
 * @summary Auth Callback
 */
export const useAuthCallback = <TError = HTTPValidationError>(
	params: AuthCallbackParams,
	options?: {
		swr?: SWRConfiguration<Awaited<ReturnType<typeof authCallback>>, TError> & {
			swrKey?: Key;
			enabled?: boolean;
		};
		request?: SecondParameter<typeof orvalFetch>;
	},
) => {
	const { swr: swrOptions, request: requestOptions } = options ?? {};

	const isEnabled = swrOptions?.enabled !== false;
	const swrKey =
		swrOptions?.swrKey ??
		(() => (isEnabled ? getAuthCallbackKey(params) : null));
	const swrFn = () => authCallback(params, requestOptions);

	const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
		swrKey,
		swrFn,
		swrOptions,
	);

	return {
		swrKey,
		...query,
	};
};
