/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Evidential Experiments API
 * OpenAPI spec version: 0.9.0
 */
import * as zod from "zod";

export const oidcClientConfigResponse = zod.object({
	authorization_endpoint: zod.string(),
	client_id: zod.string(),
	redirect_uri: zod.string(),
	scope: zod.string(),
});

export const authCallbackResponse = zod.object({
	session_token: zod.string(),
});
